### ISSUE TITLE
allow expression as array index

### ISSUE THREAD

**Issue by mmrj** [forio/flow.js#11]
related to issue #9 , possibly a duplicate

```data-f-bind="sales[<sampleInt>+1]``` (or some alternate syntax?) should work at least when sampleInt is a valid array index for sales.

**Comment by narenranjit** [comment]
With templating you can now do this by:

```
<div data-f-bind="sampleInt">
  <div data-f-bind="sales[<%= value + 1 #%]"> </div>
</div>
```

**Comment by mmrj** [comment]
verified. syntax is:
```
<div data-f-bind="vars.currentRoundIndex">
	<div data-f-bind="vars.rounds[<%= value + 1%>]"></div>
</div>
```
