### ISSUE TITLE
allow Flow.initialize() to take files parameter somewhere

### ISSUE THREAD

**Issue by mmrj** [forio/flow.js#25]
Use case is Vensim models that use external data, we want to be calling the aggregate run api with the body:
```
{ "model": "model.vmf", "files": {"data": "data.xlsx"}}
```

I tried adding this to channel.run:
```
    var options = {
        channel: {
            run: {
                model: 'model.vmf',
                account: 'acme-simulations-0',
                project: 'epicenter-615',
                files: {'data': 'data.xlsx'},
                server: { host: 'api.forio.com' } 
            }
        }
    };

    Flow.initialize(options);
```

but the request to https://api.forio.com/run/acme-simulations-0/epicenter-615/ only has model: 'model.vmf' in the body.

**Comment by narenranjit** [comment]
This worked for me:

` Flow.initialize({
          channel: { strategy: 'new-if-persisted', run: { model: "nps.vmf", files: {data: watershedDataFile}}, }
  });`

I think there was an issue in one of the versions of the js-libs in not passing the files through, try using 1.4 to see if that fixes it

**Comment by mmrj** [comment]
verified using epicenter.js 1.4
