### ISSUE TITLE
Flow Inspector: Make dragging panels smoother

### ISSUE THREAD

**Issue by narenranjit** [forio/flow.js#53]
Currently very 'choppy'

**Comment by mmrj** [comment]
tested with dist from latest master (https://github.com/forio/flow.js/commit/64b5eec6b960ee6b05f3cae2f5e80fe6739bd799), verified: 
 - chrome, both panels drag well now, whether or not your mouse is over the panel. tested with python model on local.forio.com and fml model on epicenter.com/app/. 
 - safari, only the outputs/inputs ("legend") panel appears, but it drags well now too.
