### ISSUE TITLE
Create data-f-repeat

### ISSUE THREAD

**Issue by narenranjit** [forio/flow.js#64]
Similar to foreach, but while for-each loops over it's children, repeat should loop over itself .

Usecase:

|  | 2011 | 2012| 2013 | 2014 |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Revenue   | 100 | 100 | 100 | 100 |
| Profit  | 100 | 100 | 100 | 100 |

The currently possible ways to build a financial table with variables for rows and timesteps for columns is

1)
```html
<tr data-f-foreach="Global Revenue[Product,1]">
    <td> <%= (index === 0) ? "Revenue" : '' %> <%= value %></td>
</tr>
<tr data-f-foreach="Global Profit[Product,1]">
    <td> <%= (index === 0) ? "Profit" : '' %> <%= value %></td>
</tr>
```

or

2)
 ```html
<tr data-f-foreach="Global Revenue[Product,1]">
    <%= if (index === 0) { %>
        <td> Revenue </td>
    <% } %>
    <td> <%= value %> </td>
</tr>
<tr data-f-foreach="Global Profit[Product,1]">
    <%= if (index === 0) { %>
        <td> Profit </td>
    <% } %>
    <td> <%= value %> </td>
</tr>
```

(besides building a custom attr).

"1" is a hack, and you won't be able to make the numbers in the first column properly line up.
"2" will work, but is a hassle for copy-pasting with a lot of rows.

With repeat you can:

```html
<tr>
    <td>  Revenue </td>
   <td data-f-repeat="Global Revenue[Product,1]"> </td>
</tr>
<tr>
    <td>  Profit </td>
   <td data-f-repeat="Global Profit[Product,1]"> </td>
</tr>
```

**Comment by mmrj** [comment]
testing notes: try with SimLang/Vensim (array-based) and with regular Python model

**Comment by mmrj** [comment]
tested using /dist from latest checkin (https://github.com/forio/flow.js/commit/64b5eec6b960ee6b05f3cae2f5e80fe6739bd799):

- verified works with SimLang (array-based) models:
```
<table border="1">
    <tr><td>testing data-f-repeat (#64)</td></tr>
    <tr><td>Step (using index+1 of variable)</td><td data-f-repeat="Cost[Books]"><%= index + 1 %></td></tr>
    <tr><td>enum array Cost[Books] by step</td><td data-f-repeat="Cost[Books]"></td></tr>
    <tr><td>scalar Sales by step</td><td data-f-repeat="Sales"></td></tr>
</table>
```

creates for example:
<img width="309" alt="screen shot 2015-12-28 at 10 29 40 am" src="https://cloud.githubusercontent.com/assets/1653043/12023398/f4d34966-ad4d-11e5-8ea5-12af76867d8f.png">


for Python models, you don't have builtin arrays that always grow when you advance the model. 

 - verified that for a basic array, `data-f-repeat` will display all its values, e.g. `<tr><td data-f-repeat="vars.rounds"></td></tr>` creates a cell for every value in the array `vars.rounds`.

 - verified that for an array that your model (manually) adds to each time you advance the model, `data-f-repeat` will keep adding elements, e.g. if the `advanceModel` has `newval = vars.temp[vars.currentRoundIndex] + 2; vars.temp.extend([newval])` and the ui has
```
<table border="1">
    <tr><td>testing data-f-repeat (#64)</td></tr>
    <tr><td>All rounds (using vars.rounds)</td><td data-f-repeat="vars.rounds"></td></tr>
    <tr><td>value of vars.temp</td><td data-f-repeat="vars.temp"></td></tr>
</table>
```
this displays all of the rounds initially in the top row, and then adds a new cell to the bottom row with each advancement of the model:

<img width="1199" alt="screen shot 2015-12-28 at 10 48 32 am" src="https://cloud.githubusercontent.com/assets/1653043/12023675/93579bf8-ad50-11e5-8be7-9de0e2cf383a.png">
