### ISSUE TITLE
Add 'allowPublish' flag to channel options

### ISSUE THREAD

**Issue by narenranjit** [forio/flow.js#85]
By default when you call Flow.initialize with a root DOM element it sets up the channels for 2-way binding with the UI. There are some cases when you may not want that:

- Within 'prepare' mode in simulations you may want to allow reading data to populate the chart, but dis-allow decisions (or maybe allow setting variables, but disallow operations)
- Within the UI Builder when you're in the middle of building your UI, you want to have live data to populate your template, but don't really need to/ care about sending data to the model when you're editing it.

(also consider calling the flag 'readOnly': true instead 'allowPublish': false)

**Comment by narenranjit** [comment]
@mmrj thoughts on 'readOnly' vs 'allowPublish'?

**Comment by mmrj** [comment]
@narenranjit initial reaction is that i like `readOnly` better. in my mind one of the main things that differentiates Flow.js is the automagic two-way binding: if i only want to read data, GETs are pretty easy even without Flow. so i feel like the default should be two-way, and the flag should be for `readOnly`. what do you think?

**Comment by narenranjit** [comment]
Sorry, should've been clearer - default will be two-way of course, was just debating using `readonly: false` as default vs `allowPublish: true`
