### ISSUE TITLE
Change Repeat behavior when used with existing html

### ISSUE THREAD

**Issue by narenranjit** [forio/flow.js#86]
```html
<div data-f-repeat="time">stuff</div>
```
If Time = [1,2,3], the above should probably intuitively output

```html
<div>1</div>
<div>2</div>
<div>3</div>
```

but it currently outputs
```html
<div>stuff</div>
<div>stuff</div>
<div>stuff</div>
```

If you do want it to output the latter, you should be able to just do `<div data-f-repeat="time | noop">stuff</div>` (no-op is not actually a default converter, just using it as an example)

**Comment by mmrj** [comment]
verified that we output the array values, e.g. 
```
<div data-f-repeat="sample_array">2</div>
<div data-repeat-68043="true">4</div>
<div data-repeat-68043="true">6</div>
<div data-repeat-68043="true">8</div>
```
for  sample_array = [ 2, 4, 6, 8 ] and
```
<div data-f-repeat="sample_array">stuff</div>
```

logged #90 to figure out to get 
```
<div>stuff</div>
<div>stuff</div>
<div>stuff</div>
<div>stuff</div>
```
in case that's what someone actually wants.
