### ISSUE TITLE
flow inspector: not pulling authorization information correctly (file lookup is 401)

### ISSUE THREAD

**Issue by mmrj** [forio/flow.js#89]
with flow 0.11.0 and epicenter.js 1.8.1, the flow inspector tries to 
```
GET https://api.forio.com/file/mjones/fml-test/model/model.py 
```
which returns a 401. (with epicenter.js 2.0, it tries to get /static/model.py, which is issue #88, which will eventually fail with a 404, but currently also fails with a 401.)

the correct auth token (which works in postman) is passed in the cookie, but no auth header is being passed as part of the request.

**Comment by mmrj** [comment]
example: https://forio.com/app/mjones/fml-test/flow-inspector-python.html (currently set up to use epicenter.js 2.0)

**Comment by narenranjit** [comment]
This is working as intended -- the file api does not respect the epicenter.token cookie (set through epicenter) when getting model file contents. However if you login 'locally' through epijs you'll correctly see the file contents (I added a login component to that test file to illustrate).

It may make for a more seamless experience to just have it pickup the cookie automatically; tracking that under https://issues.forio.com/browse/EPICENTER-2541 . No further action needed on this ticket either way.

**Comment by mmrj** [comment]
verified that if you are logged in as a team member (which requires you putting a login page in front of your project, e.g. from epicenter.js/dist/login) you have access to this. marking as verified and will track under epicenter-2541 moving forward.

**Comment by mmrj** [comment]
note that we have fixed this in https://issues.forio.com/browse/EPICENTER-2656 which is also https://github.com/forio/epicenter-js-libs/pull/191 : epicenter.js now uses the authorization in epicenter.token.

updated the example test page (https://forio.com/app/mjones/fml-test/flow-inspector-python.html) to use the epicenter.js version built from pr 191 and it works great.
