### ISSUE TITLE
make aliases available within templates

### ISSUE THREAD

**Issue by mmrj** [forio/flow.js#91]
related to #79 --

one of the examples there is:
```
<ul data-f-foreach="r in regions">
  <li>
      <ul data-f-foreach="s in sales">
          <li> Region <%= r %> , Sales <%= s %> </li>
      </ul>
    </li>
</ul>
```

which is somewhat more useful in the case when Sales is arrayed over Regions (rather than fixed), e.g.
```
<ul data-f-foreach="r in regions">
    <li>region <%= r %>:
        <ul data-f-foreach="s in sales">
            <li> sales <%= s[r] %></li>
        </ul>
    </li>
</ul>
```

but you currently can't reference the alias in the nested element.

**Comment by narenranjit** [comment]
This will _probably_ work

```
<ul data-f-foreach="r in regions">
    <li>region <%= r %>:
        <ul data-f-foreach="sales">
            <li data-f-bind="sales[<%= r %>]"></li>
        </ul>
    </li>
</ul>
```

This *should* work, but (probably) won't right now

```
<div data-f-bind="Sales">
    <ul data-f-foreach="r in regions">
        <li><%= Sales[r] %></li>
    </ul>
</div>
```

**Comment by mmrj** [comment]
confirmed that the "probably" doesn't quite work, but mostly because i underspecified the problem : )

here's what actually does what we want:

```
<!-- model:
 numberedRegions = [0, 1, 2, 3]
sales2d = [ [100, 101, 102, 103], [110, 111, 112, 113], [120, 121, 122, 123], [130, 131, 132, 133] ] 
-->

<ul data-f-foreach="r in numberedRegions">
    <li>region <%= r %>:
        <ul data-f-foreach="s in sales2d[<%= r %>]">
            <li><%= s %></li>
        </ul>
    </li>
</ul>
```
produces:
<img width="505" alt="screen shot 2016-11-09 at 11 37 04 am" src="https://cloud.githubusercontent.com/assets/1653043/20151908/e571e6b8-a670-11e6-8b2a-4d40a32d12d6.png">

marking this as complete/verified, and added the "should work" example to #67 for testing and variations when that issue is addressed.
